Solved all the tasks of the second block
js-tasks-ru/js-20220209_dmitrii8 pull request #2
Opened 2022-02-14 17:31 UTC by lifanov-rza

2022-02-14 17:32 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-02-15 22:15 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    } else throw new Error(`Unknown type of sortion! Value: ${param} Type: ${typeof param}`)
👍 лайк за обработку ситуации когда условия `asc/desc` не были выполнены

2022-02-15 22:15 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    let sortedArr = arr.slice().sort((a, b) => a.localeCompare(b, 'ru', {caseFirst : "upper"}));
проверьте, а точно ли тут `let`?

2022-02-15 22:16 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +        return sortByOrder(arr).reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-02-15 22:16 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    let updatedObj = Object.fromEntries(
`const`

2022-02-15 22:16 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    let updatedObj = Object.fromEntries(
`const`

2022-02-15 22:16 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-02-16 14:01 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-02-16 14:05 UTC, dosandk approved these changes
good 👍

2022-02-16 14:06 UTC, merged